### ISSUE TITLE
Rest API rate limit

### ISSUE THREAD

**Issue by mz-tinyco** [wunderlist/api#107]
Is there any rate limit on Wunderlist Rest API?  Can't find anything in the api document so I open a support ticket here to try get an answer.

**Comment by Sarke** [comment]
Good luck getting an answer here, I don't think they have any devs that look at these...

**Comment by dpetrick** [comment]
Hello @mz-tinyco, there is no rate limiting for the Rest API. Did you encounter issues that made you think there are?

Cheers,
Dom
