### ISSUE TITLE
Support smart list in API

### ISSUE THREAD

**Issue by taozhan2014** [wunderlist/api#108]
Hi,

Is there any plan to support smart list in API? Currently when you get all lists user have access to using "a.wunderlist.com/api/v1/lists", it only returns the regular list. No smart list is included.

Basically I want to be able to retrieve all tasks in a smart list using "a.wunderlist.com/api/v1/tasks?list_id=XXX" with the smart list id.

Thanks!

Tao

**Comment by schlubbi** [comment]
Hello and thanks for your question. We currently have no plans to make smart lists available through the API. Unfortunately you would need to fetch the data and filter it yourself. Hope that answers your question.
