### ISSUE TITLE
504 error 

### ISSUE THREAD

**Issue by suvarapu12** [wunderlist/api#110]
HI Team, 
![wunderlist504gatewaytimeout](https://cloud.githubusercontent.com/assets/25229735/23113434/17d6baa0-f75e-11e6-9613-fbd4814b908d.PNG)
I am integrating my application with Wunderlist. I am getting 504 gateway time out error,when I request the api for getting lists.I am attaching the screenshot.Help us to resolve this issue

**Comment by schlubbi** [comment]
I just double checked our metrics. Everything looks fine at the moment. It is possible that you run into 504s sometimes, especially when our systems are under high load. We usually mitigate problems like this rather quickly. Hope you don't run into issues anymore. Please let me know if this happens again.
