### ISSUE TITLE
Get lists call failed

### ISSUE THREAD

**Issue by harisheidiko** [wunderlist/api#111]
Hi Team ,
               I am making get lists API call, for this request I am getting 500 error response and some times successful response.I am unable to understand why 500 error response occurring sometimes.Help us to resolve this issue.Please make it high priority.I am providing error log below
Message               : Response code 500 mapped as failure.
Element               : /getWunderlistListsFlow/processors/0 
--------------------------------------------------------------------------------
Exception stack is:
Response code 500 mapped as failure. (org.mule.module.http.internal.request.ResponseValidatorException)
  org.mule.module.http.internal.request.SuccessStatusCodeValidator.validate(SuccessStatusCodeValidator.java:37)
  org.mule.module.http.internal.request.DefaultHttpRequester.validateResponse(DefaultHttpRequester.java:356)
  org.mule.module.http.internal.request.DefaultHttpRequester.innerProcess(DefaultHttpRequester.java:344)
  (307 more...)
I hope you will resolve this.Thanks in advance

**Comment by schlubbi** [comment]
Could you provide an example request that leads to the 500? The stack trace you posted looks like your code. What response message do you get along with the 500?

**Comment by schlubbi** [comment]
Please provide an example for the request you're making. What language do you use? What endpoint do you call? what headers have you set? The above stacktrace looks like framework code which isn't really helpful at all. I simply need more information in order  to understand the issue you're facing.

**Comment by harisheidiko** [comment]
Hi,
    Today I am on leave.I will send the details tomorrow
