### ISSUE TITLE
{} 400 bad request returned for exchanging code to access token

### ISSUE THREAD

**Issue by markmcwong** [wunderlist/api#113]
I tried everything I can, I already set Content-Type:application/json and have all required field in correct form. But in Postman it responses with {} in 400 Bad Request due to Bad Syntax, I tried it in my website still no luck.

Directly copied from postman:

`curl -X POST -H "Content-Type: application/json" -H "Cache-Control: no-cache" -H "Postman-Token: 64e90360-703c-8785-914a-19667b2b9290" -d '{
	"cliend_id": "518dd73af2d377583d18",
	"client_secret": "51a19ee8540b5eb840d4ddb4870bcb3a03cc49ac375***********",
	"code": "17b10b4b11549632fc830b"
}' "https://www.wunderlist.com/oauth/access_token"`

**Comment by schlubbi** [comment]
You have a type in the curl example: `cliend_id` should be `client_id`. Does this solve your issue?

**Comment by markmcwong** [comment]
It still happens and resposne with 400 of Json {} but thanks for pointing out the typo

**Comment by schlubbi** [comment]
The `code` you get back after the first step of the [authorization flow](https://developer.wunderlist.com/documentation/concepts/authorization) is temporary. Could you try to request a new code please.

**Comment by markmcwong** [comment]
You can close the case now, idk why postman is giving this error
i tried to use form append in react with axios and it doesnt work but i manually type the data and it works
