### ISSUE TITLE
Tasks list ordering 

### ISSUE THREAD

**Issue by dmkuby** [wunderlist/api#114]
Hi! 
I see that the result of the "Get Tasks for a List" operation is ordered by creation date. However, there is no references in docs. So, I want to ask, is it always true? Can I be sure that all tasks in the result list are ordered by creation date in ascending order?

Thanks.

**Comment by LunchtimeLegend** [comment]
if you haven't found your answer already, take a look at this:

https://developer.wunderlist.com/documentation/endpoints/positions

the docs outline how to order the items correctly. 

---
craig

**Comment by dmkuby** [comment]
Thanks for the reply. That article contains information about positions of tasks in the UI list. My question is little different.
1. I make API call, f.e.: "https://a.wunderlist.com/api/v1/tasks?list_id=294749978"
2. The response is array of json objects.
3. I want to take the last created task.

So, my question is, can I take the last item from the response's array? Is there a guarantee that items in this array are sorted by creation date in ascending order?

*Iterating through array to find such item is very undesired behavior for my case.

**Comment by LunchtimeLegend** [comment]
as far as i know, there is no stated guarantee. certainly, that's not the way Wunderlist itself works, so i personally wouldn't bank on it. 

--
craig

**Comment by dmkuby** [comment]
I see. Found a workaround for my task for now. Thanks again.
