### ISSUE TITLE
Where to store the client secret in a JS client app?

### ISSUE THREAD

**Issue by miguelrs** [wunderlist/api#119]
I'm writing a plugin for the email client [nylas/nylas-mail](https://github.com/nylas/nylas-mail) to send ToDos to Wunderlist.  
My plugin is written in ReactJS (like Nylas Mail) and hosted on GitHub. I've been reading about authentication in WunderlistAPI, and it seems that the client needs to send the client secret to get an access token.  

So, the only options I can think of are:  
a) Share my client secret on GitHub (hard-coded in my JS code).
b) Require each user to create an app in Wunderlist, and paste their client secrets in some options screen.
c) Create my own web server app in between the plugin and Wunderlist API.

None of those options are very nice... Are they actually the only ones, or am I missing something obvious? (sorry, I'm not expert on OAuth)

**Comment by miguelrs** [comment]
I ended up going for option c) of my previous message 👆   

Instead of creating a normal website, I used [prose/gatekeeper](https://github.com/prose/gatekeeper), which (as far as I understand) is basically a small NodeJS app that runs on the server and accepts request from the client including the Wunderlist code, fetches the access token using the client secret, which is stored as an environment variable, and returns the access token to the client... It also includes a Heroku button, so it's very easy to install...

However, for some reason the original repo doesn't work with WunderlistAPI, but I created a fork [miguelrs/gatekeeper-request](https://github.com/miguelrs/gatekeeper-request), which uses a different library to make the OAuth request, and it seems to work fine...

**Comment by akanshgulati** [comment]
@miguelrs have you tried to sync application on cross platforms using sockets or long polling? How are you managing it?

**Comment by miguelrs** [comment]
@akanshgulati tbh the plugin I wrote is a bit abandoned, since I'm not using Nylas Mail anymore (actually Nylas Mail itself got abandoned, although there are some forks for which the plugin should work).  

Anyway, to answer your question: no, I didn't try sockets/polling - as far as I can remember, the "sync" process in the plugin it's the most rudimentary approach ever, which is basically a timeout of 10min, after which I call the API again...  
I think this is the bit:  
https://github.com/miguelrs/nylas-wunderlist/blob/582f44cac1d0dd581ebba52ebdbc7a18b72fb265/lib/stores/WunderlistAuthStore.es6#L71
