### ISSUE TITLE
Winforms

### ISSUE THREAD

**Issue by bhman792** [wunderlist/api#137]
Might be the dumbest question ever, but can I use the Wunderlist API in a C# winforms application?

Thanks

**Comment by dschneider** [comment]
Hello :wave: Yes, you can basically use the Wunderlist API in any application. You just need to create an application here: https://developer.wunderlist.com/apps and follow the docs on authorization: https://developer.wunderlist.com/documentation/concepts/authorization and use an HTTP client to talk to the server.

Cheers
