### ISSUE TITLE
Authorization issue if user already granted access

### ISSUE THREAD

**Issue by alpipego** [wunderlist/api#17]
I have a problem with the authorization concept described here: https://developer.wunderlist.com/documentation/concepts/authorization
I.e. after granting access to my application once, all other subsequent calls to the URL from "1" (https://www.wunderlist.com/oauth/authorize?client_id=ID&redirect_uri=URL&state=RANDOM) return a "403 - Forbidden".

1. In a dev environment I have the problem that I granted access to the app but did not record the returned code and now I can't test this further (see also https://twitter.com/alpipego/status/660092047664275456)

2. After releasing my app to the public, if a user that has already authorized it and clicks on the button again, they get a "FORBIDDEN" page. How can I prevent this?

**Comment by alpipego** [comment]
Alright; sorry for this: completely my fault. I guess it's best if you delete this so no one gets confused...

**Comment by vsmart** [comment]
Glad you got it to work @alpipego!

**Comment by andreterron** [comment]
I'm also having this problem. Can you explain what was wrong, and how you fixed it, please? thanks!

**Comment by alpipego** [comment]
@andreterron check if your app url and (I guess more importantly) your __auth callback url__ match the url you're sending the request from. After adding my local development url it worked for me.

**Comment by andreterron** [comment]
Thanks @alpipego! It worked here, I was trying to redirect to another subdomain.

**Comment by adamrenklint** [comment]
:+1:

**Comment by wmhtun** [comment]
Hi, I've a problem in authorization process from my web app. I set app url (http://localhost:63021/Service.asmx) and callback url to (http://localhost:63021/Service.asmx/callback)

when I try to request https://www.wunderlist.com/oauth/authorize?client_id=ID&redirect_uri=URL&state=RANDOM this link, response is wunderlist login html string (i.e https://www.wunderlist.com/login ...)

I cannot get response code that need to exchange for accesstoken. Pls help me. Thanks
