### ISSUE TITLE
Creating developer app returns a 500 error

### ISSUE THREAD

**Issue by newnottakenname** [wunderlist/api#19]
When going to https://developer.wunderlist.com/apps and using the following data:

**Name:** Zeus
**Description:** Something something sync
**App img:** none
**App url:** https://developer.wunderlist.com
**Auth callback url:** wunderlist://

then I get redirected to a page, which says:

"We're sorry, but something went wrong."
"If you are the application owner check the logs for more information."

Confirmed on Firefox and Chrome

Have a great day

**Comment by newnottakenname** [comment]
@duncan Has anything been done on this issue?

**Comment by adamrenklint** [comment]
The callback url is not valid. If you don't have a http/https url for us to redirect to (maybe you are just generating an app to get an access token), you can put ```https://developer.wunderlist.com``` there also.
