### ISSUE TITLE
Unable to authenticate 

### ISSUE THREAD

**Issue by jcbmllgn** [wunderlist/api#21]
I'm having trouble authenticating with your API. I've registered an app and am following the directions found [here](https://developer.wunderlist.com/documentation/concepts/authorization).

I'm redirecting users to this URL:
https://www.wunderlist.com/oauth/authorize?client_id=5e545e44e8cdc3ecd428&http://localhost:3000/&state=derp

However this returns an error "Forbidden":
![screen shot 2015-11-24 at 7 15 10 pm](https://cloud.githubusercontent.com/assets/1261230/11400171/c0acbcc0-9359-11e5-8572-3cf5d0efe2e3.png)

What am I doing wrong?

Thanks for the help - Jacob

**Comment by idpaterson** [comment]
That URL looks corrupt, try `https://www.wunderlist.com/oauth/authorize?client_id=5e545e44e8cdc3ecd428&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2F&state=derp` instead. Note that `redirect_uri=` was missing in your original authorization URL and the localhost redirect was not encoded (as with `encodeURIComponent()`)

**Comment by adamrenklint** [comment]
Agree with @idpaterson, the url is not properly formatted. Escape the ```redirect_uri``` and it should work.

**Comment by andreterron** [comment]
@adamrenklint, I'm having the same problem, even with a escaped url. When I'm logged in with my user (which I could authorize yesterday), and I enter this URL: https://www.wunderlist.com/oauth/authorize?client_id=601cf6003f40d8a63c0e&redirect_uri=http%3A%2F%2Fwww.example.com&state=herp

I get the Forbidden error

**Comment by adamrenklint** [comment]
Is the redirect host and url the same as the callback url on developer.wunderlist.com?

**Comment by andreterron** [comment]
Problem solved, I was missing the right subdomain. Sorry for the trouble. Thanks for pointing it out!

**Comment by jcbmllgn** [comment]
:face_palm: Thanks for the help.

**Comment by wmhtun** [comment]
Hi, I've a problem in authorization process from my web app. I set app url (http://localhost:63021/Service.asmx) and callback url to (http://localhost:63021/Service.asmx/callback)

when I try to request https://www.wunderlist.com/oauth/authorize?client_id=ID&redirect_uri=URL&state=RANDOM this link, response is wunderlist login html string (i.e https://www.wunderlist.com/login ...)

I cannot get response code that need to exchange for accesstoken. Pls help me. Thanks

PS: I pass the same callback url from registration in http request
