### ISSUE TITLE
Update Reminder Task Error

### ISSUE THREAD

**Issue by bagtim** [wunderlist/api#22]
Hello, i want update reminder for task in Wunderlist. Use Wunderlist Api:

curl -H "Content-Type: application/json" -H "X-Access-Token: xxx" -H "X-Client-ID: xxx" a.wunderlist.com/api/v1/reminders/12345 -X PATCH -d '{"revision":1,"date":"2015-11-25T16:49:23"}'

and respone:

{"error":{"type":"not_found","translation_key":"api_error_not_found","message":"The resource you requested could not be found."}}

**Comment by bagtim** [comment]
Please, Check this function

**Comment by adamrenklint** [comment]
The reminder ID in your example is probably not a valid ID for a reminder that you (or the user you act on behalf of) have permission for. Try ```/api/v1/reminders?task_id=xxx``` with the ID of the task where the reminder is supposed to be attached to, and check the ID in the response.

**Comment by bagtim** [comment]
![default](https://cloud.githubusercontent.com/assets/9790826/11502588/d416abc0-984c-11e5-8fe2-54a52ede90df.png)

**Comment by bagtim** [comment]
where
1494997180 - task_id
103758387 - reminder id

**Comment by bagtim** [comment]
![default](https://cloud.githubusercontent.com/assets/9790826/11502654/28229b7a-984d-11e5-9787-c06ea80a83fd.png)

**Comment by adamrenklint** [comment]
When doing a PATCH, you should use this url format: ```a.wunderlist.com/api/v1/reminders/:id```.

**Comment by bagtim** [comment]
![default](https://cloud.githubusercontent.com/assets/9790826/11502806/070b4774-984e-11e5-8365-f839625d7a7c.png)
