### ISSUE TITLE
Move task to another list 

### ISSUE THREAD

**Issue by romangetman** [wunderlist/api#25]
The `PATCH a.wunderlist.com/api/v1/tasks/:id` doesn't seem to accept a `list_id` parameter. 

Is there a (proper) way to move a task to another list, without deleting it from one list and re-creating in another?

**Comment by daniel-marschner** [comment]
@romangetman could you please post your whole JSON body so we can check back on that issue. FYI a possible reason this could fail is a missing `revision` parameter in the request body. Thanks for your support!

**Comment by romangetman** [comment]
@daniel-marschner I've re-checked my code and found that `list_id` was being sent as a string and that was causing the problem. Moving now works. However what was confusing at first is that `list_id` is not listed here `https://github.com/wunderlist/api/blob/master/endpoints/task.md` as a possible argument for editing.

**Comment by daniel-marschner** [comment]
Fantastic - thanks for the hint, we will adjust the documentation! :+1:
