### ISSUE TITLE
Typo in documented POST Webhook URL

### ISSUE THREAD

**Issue by passuf** [wunderlist/api#30]
In the [Webhook Docs](https://developer.wunderlist.com/documentation/endpoints/webhooks) it is stated that the URL to create a new webhook is:
```
POST a.wunderlist.com/api/v1/webhoooks
```

But instead it should be:
```
POST a.wunderlist.com/api/v1/webhooks
```

**Comment by vsmart** [comment]
Thank you for finding this one! The place to fix this would be here: https://github.com/wunderlist/api/blob/master/endpoints/webhooks.md#create-a-webhook 
Do you want to submit a PR?
