### ISSUE TITLE
Get folder that contains the list

### ISSUE THREAD

**Issue by tollmanz** [wunderlist/api#34]
I need to be able to figure out which folder a list is in. When using the `/lists` or `/lists/:id` endpoint, the returned data does not include a `folder` property. I see that I can query `/folders` and iterate over the folders to figure out which one contains the list.

My question is, am I missing something in the API that makes it easier to find a list's folder? If not, would it be possible to add the folder property to data returned by the `/lists` endpoint?

**Comment by vsmart** [comment]
Hi @tollmanz 
Yes you are correct - the lists don't contain references to folders and afaik we do not plan to add that property to the list. You will have to check /folders to see which folder your list is currently in. 
Hope this helps. 
Cheers
