### ISSUE TITLE
Bad Request on retrieving a Note for a specific task in PHP

### ISSUE THREAD

**Issue by realbase** [wunderlist/api#39]
Trying to get a note from a task via PHP, but cannot get it to work. 
Adding tasks, updating tasks, retrieving lists, and adding a note works flawlessly.  

But when is want to *get* (retrieve) a note for a specific task, I get a 400-Bad-Request. 

```
//result of var_dump($context)
/*
array(1) {
  ["http"]=>
  array(3) {
    ["method"]=>
    string(3) "GET"
    ["header"]=>
    string(178) "X-Client-ID: /* XXXXXMY-CLIENT-IDXXXXX */
X-Access-Token: /* XXXXXXMY-ACCESS-TOKENXXXX */ 
Content-Type: application/json; charset=utf-8
Content-Length: 22"
    ["content"]=>
    string(22) "{"task_id":1234567890}"
  }
}
*/
```

then i use
```
        $url = 'https://a.wunderlist.com/api/v1/notes';
        $result = file_get_contents($url, false, stream_context_create($context));
        return json_decode($result, true);
```

It returns:

```
Warning:  file_get_contents(https://a.wunderlist.com/api/v1/notes): failed to open stream: 
HTTP request failed! HTTP/1.1 400 Bad Request
 in /home/.../public_html/wunderlist/wunderlist.php on line 90
```
Something i'm missing?

**Comment by schlubbi** [comment]
I don't know PHP well enough, but it looks like you're trying to set the content for an HTTP GET request instead of providing the `task_id` as a query parameter of the URL. Maybe try `$url = 'https://a.wunderlist.com/api/v1/notes?task_id= 1234567890';` instead?

**Comment by realbase** [comment]
Yes, thanks, got it working!
