### ISSUE TITLE
if i add todo from REST api it gets listed last into wuderlist official webapp. when i add todo from wunderlist  webapp it gets listed first on list. how to make it listed first from REST call?

### ISSUE THREAD

**Issue by sasukepatel** [wunderlist/api#41]

**Comment by zedgoat** [comment]
The webapp probably manages the position after the task has been added based on the users first / last preference. If you're doing it through the API you will need to do some further work [using the positions API](https://developer.wunderlist.com/documentation/endpoints/positions) to set things how you want them.

**Comment by sasukepatel** [comment]
Got it. did sorting on client side. tnx
