### ISSUE TITLE
Is a read-only scope available through OAuth2?

### ISSUE THREAD

**Issue by thbar** [wunderlist/api#45]
For some purposes, it's not necessary to have a write-enabled token, and a read-only one would be enough.

I did not see that on the [documentation](https://developer.wunderlist.com/documentation/concepts/authorization).

Is it although available maybe in beta form, or planned?

**Comment by duncan** [comment]
Currently, we don't have scopes defined. I totally agree with you that they're needed. I don't have any plans I can share at this point, however.
