### ISSUE TITLE
Are there any examples for the delete task api?

### ISSUE THREAD

**Issue by CurlingForFun** [wunderlist/api#47]
i am just using cygwin curl, and i have been able to create and update tasks with similar curls, but the delete task method just returns a missing parameter (revision). I have been sending the revision the same way as the other methods i have working... The revision id is correct. 

Sample curl...
curl -H "Content-Type: application/json" -H "X-Access-Token: secret" -H "X-Client-ID: nottelling" -X DELETE -d '{"revision": 2}' https://a.wunderlist.com/api/v1/tasks/123

spits back a 400 
{"error":{"type":"missing_parameter","translation_key":"api_error_missing_params","message":"Missing parameter.","revision":["required"]}}

**Comment by nzufelt** [comment]
I have found that deleting a task requires `revision` to be a string, even though they say it should be an int.  Some other delete calls require `revision` to a string, and the docs explicitly state this (e.g. folders, see issue #42).  This is likely a bug, but see if you can reproduce this by changing your 
`'{"revision": 2}'` 
to 
`'{"revision": "2"}'`.

**Comment by CurlingForFun** [comment]
Hmm i didn't have much luck with a string either, just another 400 error. Not sure where to go from here, i assume it is working for others users. This script has moved to a unix host now and still produceses a 400 code.

**Comment by thy1985** [comment]
A HTTP DELETE has no data, it is more like a GET not a POST

So you pass in parameters not data:
```
curl -H "Content-Type: application/json" -H "X-Access-Token: secret" -H "X-Client-ID: alsosecret" -X DELETE   https://a.wunderlist.com/api/v1/tasks/<taskid>?revision=1
```

**Comment by CurlingForFun** [comment]
@thy1985 , you are correct. making that adjustment to the curl script has it happily deleting finished tasks. DELETE is not a method i use frequently. Thanks for help!
