### ISSUE TITLE
Endpoint to get user details by user id

### ISSUE THREAD

**Issue by tgdavies** [wunderlist/api#49]
As far as I can tell there is no way to restrict the output of https://a.wunderlist.com/api/v1/users to a single user -- I want to do this as I'm processing event data via a webhook and I'd like to convert the user_id to a name without retrieving all the users.

**Comment by vsmart** [comment]
Hi @tgdavies, as you suspected, this endpoint will return all users that your user has access to. You will have to filter out the information on your end. 
Cheers
