### ISSUE TITLE
Add task to top of list

### ISSUE THREAD

**Issue by stdavis** [wunderlist/api#53]
When I add a new task via the web api it goes on the bottom of the list. When I add a new task via the UI it goes on the top of the list. I wish that the web api behaved like the UI.

Thanks for the awesome product!

**Comment by jasonkotenko** [comment]
We also have a user asking for this (I work on the Platform team at Zapier).  It would be preferable if the API would follow the setting shown in the web UI:

![top of list setting](https://zapier.cachefly.net/storage/photos/3d3222efe6cbd3aff6a54128ccb1aa50.png)

Less intuitive, but still useful, would be a simple flag on the Task API to allow the caller to specify top or bottom of list.

**Comment by stdavis** [comment]
This would be great. As a temporary work around, I've had to [reorder](https://github.com/wunderlist/api/blob/master/endpoints/positions.md) the list each time I add a new one.

**Comment by ericyahhh** [comment]
Currently our client apps look at the user's setting for top/bottom and add it to the correct position.
