### ISSUE TITLE
Reminder recurrence

### ISSUE THREAD

**Issue by shahjabeen-elevate** [wunderlist/api#56]
Can I set recurring reminders, for example if I have a task which I need to perform daily, and I need to add daily reminders?

**Comment by ericyahhh** [comment]
Currently it's only possible to set recurring due dates. However, if you set a reminder in addition the reminder will automatically re-occur and adjust when you check off a recurring task.

**Comment by ericyahhh** [comment]
@qadirsuh There you go: https://github.com/wunderlist/api/blob/master/endpoints/task.md#update-a-task-by-overwriting-properties
