### ISSUE TITLE
Allow API operations to be performed as if by a particular user

### ISSUE THREAD

**Issue by tgdavies** [wunderlist/api#57]
In our integration of Wunderlist with HipChat we allow a task to be completed by a / command -- /wunderlist complete <taskid>.

At the point at which we make the REST call to Wunderlist we may be able to map the HipChat user to a Wunderlist user, but as far as I can tell there is no way to ask Wunderlist to consider the command as coming from a particular user -- just the user who originally authorised the integration's access to Wunderlist.

That is, I'd like the 'client.user_id' in the resulting webhook call to match what I gave. (I could record some state and match it up when I get the webhook, but I'd prefer a simpler solution)

Am I missing a way to do this?

**Comment by vsmart** [comment]
Hi @tgdavies, Sorry to say, as far as I'm aware there is no option to impersonate the user in the way you are describing at the moment.
