### ISSUE TITLE
Activity or History API?

### ISSUE THREAD

**Issue by t1mmen** [wunderlist/api#58]
Hi,

As part of the integration with www.gotdone.me (a time tracking assistant), I'm looking for a way to display the activity log of a user.

Typically, this would include things like the user...
* ... completing a todo
* ... updating a todo
* ... deleting a todo
* ... creating a todo

Is this something that's currently possible? Or would the best approach perhaps be to look at the webhook API?

**Comment by ericyahhh** [comment]
This hasn't been documented yet. I'd suggest to look into the web hook API to achieve this.
