### ISSUE TITLE
Get all the lists from the Wunderlist API : a.wunderlist.com/api/v1/lists

### ISSUE THREAD

**Issue by JgdshSeerm** [wunderlist/api#64]
Hi,

I got the access_token, but after that i want to get the lists and tasks, but in the documentation GET **a.wunderlist.com/api/v1/lists** to get the lists.

I wonder how to get the lists, please help me

**Comment by mehulsbhandari** [comment]
Hi its working for me 

curl -H "X-Access-Token: XXXXX" -H "X-Client-ID: XXXXX" https://a.wunderlist.com/api/v1/lists
