### ISSUE TITLE
Create note/comment as same time as task

### ISSUE THREAD

**Issue by taskclone** [wunderlist/api#67]
We currently use email to create tasks with notes in Wunderlist which works great.  Would like to use the API instead, but trying to understand how to create a new task and note at same time given note needs id of task which we don't have.  

Todoist uses temp ids to solve this and wondering if there is a reasonable solution with  Wunderlist API?

**Comment by zedgoat** [comment]
Don't think it can be done on v1, you will be limited to executing the task creation, then using the ID in the response to then generate a req. to populate the note. If you need a single endpoint for this you would probably need to wrap it in your own API that handles the request / response / request sequence to create it all from one external request.

I'm doing similar in Go where I have an intermediate API that bundles up some of the activities into a single call, exposed on a local web server.

**Comment by vsmart** [comment]
@zedgoat is correct, you'll need to make two separate api calls.
