### ISSUE TITLE
Create task not working.

### ISSUE THREAD

**Issue by frestalink** [wunderlist/api#68]
Hello!

I need to create a task in Wunderlist. I tried various examples from the documentation, but I could not solve this problem. I think I’m doing something wrong.

Maybe someone has a simple php code example for create a task in Wunderlist using Wunderlist API?

Thanks

![taskcreate](https://cloud.githubusercontent.com/assets/19640842/15638585/4a8d76e2-25f8-11e6-90a5-c62862077731.jpg)

**Comment by vsmart** [comment]
Hi @frestalink, what error message are you seeing?

**Comment by frestalink** [comment]
Uncaught ReferenceError: require is not defined in index3.php 15

line 15
15      var TasksService = require('services/Tasks');

**Comment by frestalink** [comment]
I changed all my code and its working now. Thanks
