### ISSUE TITLE
How can I retrieve Today/ Week lists using the API?

### ISSUE THREAD

**Issue by shaakunthala** [wunderlist/api#73]
I was expecting `GET a.wunderlist.com/api/v1/lists/today` to work just as the URL https://www.wunderlist.com/webapp#/lists/today

Can this be fixed please?

Thanks!
Shaakunthala

**Comment by vsmart** [comment]
Hi @shaakunthala -
We don't offer a REST endpoint for the Today and Week smart lists. You need to fetch the tasks and generate these views on the client side using the information on the tasks' due date.
