### ISSUE TITLE
Getting Errors while creating webhooks and  some operations based on  API

### ISSUE THREAD

**Issue by harisheidiko** [wunderlist/api#74]
I am trying to create webhooks,get lists,creating lists in wunderlist am getting errors.
{
  "error": {
    "type": "server_error",
    "translation_key": "api_error_unknown",
    "message": "An unknown server error occurred",
    "authentication": [
      "missing"
    ]
  }
}
 Suggest me how to overcome this

**Comment by dschneider** [comment]
Hello @harisheidiko! The response says the authentication is missing. Did you go through the authentication process as described here? -> https://developer.wunderlist.com/documentation/concepts/authorization

**Comment by harisheidiko** [comment]
Hi,
   I had done authentication process as mentioned in the above url.I got
access token also.I got problem in web hook creation.Thank you for your
valuable reply.
