### ISSUE TITLE
Custom fields on task via REST API

### ISSUE THREAD

**Issue by yesil** [wunderlist/api#83]
Having custom fields on Tasks would ease the integration with external systems.

**Comment by cmlindstrom** [comment]
Second this - helps to 'stamp' objects to maintain uniqueness across clients.

**Comment by schlubbi** [comment]
Thanks for the suggestion but currently there are no plans to add a feature like this to the API. I'll add it to our internal list of feature requests tho.

**Comment by cmlindstrom** [comment]
Thanks for the direction - hope your internal folks elect to add the feature.  The issue that this feature helps to avoid is inadvertently adding a duplicate object to the list from the client when the time sync get's out of whack.
