### ISSUE TITLE
Open Authentication Not Working

### ISSUE THREAD

**Issue by dlevinson5** [wunderlist/api#9]
Until a few days ago I could provide a port number as part of the redirect_ui parameter. As of today this i not working. I have a local desktop application that depends on being able to redirect the authentication back to http://loalhost:8094/oauth.

This was again working until recently and it appears that your server side redirect is removing the port information from the redirect. 

How can I get back this functionality?

**Comment by duncan** [comment]
Thanks for the report. That's definitely a bug that we'll look into.

**Comment by idpaterson** [comment]
I have received several bug reports for this problem which is affecting my application as well [as noted here](https://github.com/idpaterson/alfred-wunderlist-workflow/issues/82). Thanks for looking into it.

**Comment by rotev** [comment]
I confirm that this issue was caused by a recent change to our API, and I'm currently working to fix it.

**Comment by rotev** [comment]
@dlevinson5, @idpaterson, this bug is fixed now!

**Comment by idpaterson** [comment]
@rotem, thank you! I can confirm the fix, this looks good on my end.
