### ISSUE TITLE
400 Bad Request when Getting Auth Code

### ISSUE THREAD

**Issue by rosshardy** [wunderlist/api#92]
Hello, Wunderlist. I'm trying to integrate an app (Amazon Echo skill) using OAUTH and am getting stuck getting the access token. I can see using Chrome Dev tools that I'm getting a code back after user logs in, but when I attempt the POST to get the access token using POSTMAN or CURL I'm getting 400 bad request. I have copy/pasted the client secret and id from the app page on Wunderlist, and the code is the one I'm seeing in the redirect after log in. Content-type is 'application/json'. I'm not sure how to further debug here. My app account is echowunderlist@gmail.com. 

I'm trying to get the auth code manually because Alexa OAUTH is failing so I'm trying to intervene manually to make sure the auth code is returned but I'm not seeing it.

**Comment by Iskalla** [comment]
I'm getting a 404 - Not Found when trying to access https://www.wunderlist.com/oauth/access_token in any way

**Comment by rosshardy** [comment]
I was using the wrong client ID and secret. Thank you.
