### ISSUE TITLE
Webhook Creation fialed

### ISSUE THREAD

**Issue by harisheidiko** [wunderlist/api#93]
I am trying to create webhook  by hitting the url "a.wunderlist.com/api/v1/webhooks",by proving body and authorization based on api.But I am getting 404 error.Help me to resolve this issue.Quick help is needed.Thanks in advance

**Comment by harisheidiko** [comment]
Hi,

**Comment by harisheidiko** [comment]
Hi,
    May be server down issue with wunderlist side.Now working fine

**Comment by harisheidiko** [comment]
Hi,
   Today i am facing same problem with wunderlist Api.Some times it's working,some times getting 404 error.We are facing diifficulty with this inconsistent behaviour.Quick help is needed.thanks in advance

**Comment by akanshgulati** [comment]
@harisheidiko do u have idea about keeping application sync on cross platforms with existing sockets for Wunderlist? Are you using sockets or http for this?

**Comment by harisheidiko** [comment]
Hi,
    I don't have idea about sockets. I am using http. Can u briefly explain
about how to connect sockets. Thanks
