### ISSUE TITLE
Are there any plans to create API for backups?

### ISSUE THREAD

**Issue by AndreyKozhevnikov** [wunderlist/api#95]
Hi,

Do you have any plans to provide API to create backups? (simple method GetBackupString() will be enough :) )

Thanks,
Andrey

**Comment by schlubbi** [comment]
As you mentioned correctly there is no officially documented API to export data. 
@zedgoat recommendation is correct tho. You could leverage the `https://backup.wunderlist.com/api/v1/export` endpoint to get your data as a JSON blob. The necessary information is correctly provided by @zedgoat.
