### ISSUE TITLE
Persistent popups and alarms request

### ISSUE THREAD

**Issue by stepnjump** [wunderlist/api#99]
Hi guys,

I'm not sure if this is the right place to write this but I would have a suggestion.
I really like the application however, I think it would be really great if there was a way to provide for persistent alarms.
What happens is when my phone vibrates, sometimes I don't have it on me. It only vibrates once. So when I get back, I might have missed an important alarm since I don't always use my cell phone during the day. 
Same thing happens with the chrome extension. The popups are showing for 10 seconds and then they disapears. Is there any way to let it float there at the bottom right of my screen until I either snooze it or dismiss it?

Thank you very much.

StepNjump

**Comment by FelipeBarrosCruz** [comment]
I have the same opinion, wold be a excellent functionality.
The alarm clocks is primary to help with user experience.
If the team need help with this, contact me, I'm propose to help.

**Comment by schlubbi** [comment]
Thanks for the suggestion. You might as well use https://wunderlist.uservoice.com to voice your idea. I put the idea on our internal list of feature ideas.

Thanks again.

**Comment by stepnjump** [comment]
You are welcome
